export let ideacontest = [
  {
    id: 1,
    contest_name: "지각 방지 서비스 <단디>를 소개합니다",
    contest_image: "test1",
    registrant: "g1",
    registrant_image: "test2",
    resgist_date: new Date(2023, 2, 1, 7, 31, 10, 22),
    hits: 5,
    thumbs: 1,
    scrap:3,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 2,
    contest_name: "방지 서비스 <단디>를 소개합니다",
    contest_image: "test2",
    registrant: "g2",
    registrant_image: "test1",
    resgist_date: new Date(2023, 2, 1, 11, 31, 10, 22),
    hits: 5,
    thumbs: 5,
    scrap:1,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 3,
    contest_name: "서비스 <단디>를 소개합니다",
    contest_image: "test3",
    registrant: "g3",
    registrant_image: "test7",
    resgist_date: new Date(2023, 0, 30, 12, 31, 10, 22),
    hits: 5,
    thumbs: 2,
    scrap:2,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 4,
    contest_name: "단디를 소개합니다",
    contest_image: "test4",
    registrant: "g4",
    registrant_image: "test6",
    resgist_date: new Date(2023, 0, 30, 5, 25, 10, 22),
    hits: 6,
    thumbs: 7,
    scrap:2,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 5,
    contest_name: "소개합니다",
    contest_image: "test5",
    registrant: "g5",
    registrant_image: "test3",
    resgist_date: new Date(2023, 0, 30, 1, 31, 9, 22),
    hits: 7,
    thumbs: 12,
    scrap:2,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 6,
    contest_name: "지각 방지",
    contest_image: "test6",
    registrant: "g6",
    registrant_image: "test8",
    resgist_date: new Date(2023, 0, 29, 12, 22, 9, 22),
    hits: 6,
    thumbs: 0,
    scrap:4,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 7,
    contest_name: "ㄴㄹㅇ",
    contest_image: "test7",
    registrant: "g7",
    registrant_image: "test4",
    resgist_date: new Date(2023, 0, 29, 5, 1, 9, 22),
    hits: 4,
    thumbs: 1,
    scrap:5,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기획/아이디어",
  },
  {
    id: 8,
    contest_name: "b",
    contest_image: "test8",
    registrant: "g8",
    registrant_image: "test8",
    resgist_date: new Date(2023, 0, 3, 1, 31, 9, 22),
    hits: 9,
    thumbs: 5,
    scrap:0,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"기타 아이디어",
  },
  {
    id: 9,
    contest_name: "m",
    contest_image: "test8",
    registrant: "g9",
    registrant_image: "test5",
    resgist_date: new Date(2023, 0, 2, 1, 31, 9, 22),
    hits: 10,
    thumbs: 4,
    scrap:1,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"디자인",
  },
  {
    id: 10,
    contest_name: "a",
    contest_image: "test1",
    registrant: "g10",
    registrant_image: "test7",
    resgist_date: new Date(2023, 0, 1, 1, 31, 9, 22),
    hits: 9,
    thumbs: 1,
    scrap:3,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"영상",
  },
  {
    id: 11,
    contest_name: "c",
    contest_image: "test3",
    registrant: "g11",
    registrant_image: "test2",
    resgist_date: new Date(2022, 11, 30, 1, 31, 9, 22),
    hits: 8,
    thumbs: 2,
    scrap:2,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"광고/마케팅",
  },
  {
    id: 12,
    contest_name: "v",
    contest_image: "test6",
    registrant: "g12",
    registrant_image: "test6",
    resgist_date: new Date(2022, 11, 27, 1, 31, 9, 22),
    hits: 7,
    thumbs: 3,
    scrap:1,
    detail_regist:"단국대학교 SW중심대학 경소톤",
    detail_result:"출품작",
    detail_category:"광고/마케팅",
  },
];

export function getIdeaContests() {
  return ideacontest;
}