let ideacontest = [
  {
    id: 1,
    contest_name: "DB공모전",
    contest_image: "test1",
    registrant: "호갱1",
    registrant_image: "test2",
    resgist_date: new Date("2023-1-31"),
    hits: 5,
    thumbs: 1,
    scrap:3,
  },
  {
    id: 2,
    contest_name: "아이디어 공모전",
    contest_image: "test2",
    registrant: "호갱2",
    registrant_image: "test1",
    resgist_date: new Date("2023-1-30"),
    hits: 1,
    thumbs: 5,
    scrap:1,
  },
  {
    id: 3,
    contest_name: "DB공모전",
    contest_image: "test3",
    registrant: "호갱3",
    registrant_image: "test7",
    resgist_date: new Date("2023-1-29"),
    hits: 2,
    thumbs: 2,
    scrap:2,
  },
  {
    id: 4,
    contest_name: "DB공모전",
    contest_image: "test4",
    registrant: "호갱4",
    registrant_image: "test6",
    resgist_date: new Date("2023-1-28"),
    hits: 6,
    thumbs: 7,
    scrap:2,
  },
  {
    id: 5,
    contest_name: "DB공모전",
    contest_image: "test5",
    registrant: "호갱1",
    registrant_image: "test3",
    resgist_date: new Date("2023-1-27"),
    hits: 7,
    thumbs: 12,
    scrap:2,
  },
  {
    id: 6,
    contest_name: "DB공모전",
    contest_image: "test6",
    registrant: "호갱1",
    registrant_image: "test8",
    resgist_date: new Date("2023-1-27"),
    hits: 6,
    thumbs: 0,
    scrap:4,
  },
  {
    id: 7,
    contest_name: "DB공모전",
    contest_image: "test7",
    registrant: "호갱1",
    registrant_image: "test4",
    resgist_date: new Date("2023-1-27"),
    hits: 4,
    thumbs: 1,
    scrap:5,
  },
  {
    id: 8,
    contest_name: "DB공모전",
    contest_image: "test8",
    registrant: "호갱1",
    registrant_image: "test8",
    resgist_date: new Date("2023-1-27"),
    hits: 9,
    thumbs: 5,
    scrap:0,
  },
  {
    id: 9,
    contest_name: "DB공모전",
    contest_image: "test8",
    registrant: "호갱1",
    registrant_image: "test5",
    resgist_date: new Date("2023-1-27"),
    hits: 10,
    thumbs: 4,
    scrap:1,
  },
  {
    id: 10,
    contest_name: "DB공모전",
    contest_image: "test1",
    registrant: "호갱1",
    registrant_image: "test7",
    resgist_date: new Date("2023-1-27"),
    hits: 9,
    thumbs: 1,
    scrap:3,
  },
  {
    id: 11,
    contest_name: "DB공모전",
    contest_image: "test3",
    registrant: "호갱1",
    registrant_image: "test2",
    resgist_date: new Date("2023-1-27"),
    hits: 8,
    thumbs: 2,
    scrap:2,
  },
  {
    id: 12,
    contest_name: "DB공모전",
    contest_image: "test6",
    registrant: "호갱1",
    registrant_image: "test6",
    resgist_date: new Date("2023-1-27"),
    hits: 7,
    thumbs: 3,
    scrap:1,
  },
];

export function getIdeaContests() {
  return ideacontest;
}