let ideacontest = [
  {
    id: 1,
    contest_name: "h",
    contest_image: "test1",
    registrant: "호갱1",
    registrant_image: "test2",
    resgist_date: new Date(2023, 2, 2, 12, 31, 10, 22),
    hits: 5,
    thumbs: 1,
    scrap:3,
  },
  {
    id: 2,
    contest_name: "d",
    contest_image: "test2",
    registrant: "호갱2",
    registrant_image: "test1",
    resgist_date: new Date(2023, 2, 1, 12, 31, 10, 22),
    hits: 1,
    thumbs: 5,
    scrap:1,
  },
  {
    id: 3,
    contest_name: "d",
    contest_image: "test3",
    registrant: "호갱3",
    registrant_image: "test7",
    resgist_date: new Date(2023, 0, 30, 12, 31, 10, 22),
    hits: 2,
    thumbs: 2,
    scrap:2,
  },
  {
    id: 4,
    contest_name: "o",
    contest_image: "test4",
    registrant: "호갱4",
    registrant_image: "test6",
    resgist_date: new Date(2023, 0, 30, 5, 25, 10, 22),
    hits: 6,
    thumbs: 7,
    scrap:2,
  },
  {
    id: 5,
    contest_name: "p",
    contest_image: "test5",
    registrant: "호갱5",
    registrant_image: "test3",
    resgist_date: new Date(2023, 0, 30, 1, 31, 9, 22),
    hits: 7,
    thumbs: 12,
    scrap:2,
  },
  {
    id: 6,
    contest_name: "l",
    contest_image: "test6",
    registrant: "호갱6",
    registrant_image: "test8",
    resgist_date: new Date(2023, 0, 29, 12, 22, 9, 22),
    hits: 6,
    thumbs: 0,
    scrap:4,
  },
  {
    id: 7,
    contest_name: "j",
    contest_image: "test7",
    registrant: "호갱7",
    registrant_image: "test4",
    resgist_date: new Date(2023, 0, 29, 5, 1, 9, 22),
    hits: 4,
    thumbs: 1,
    scrap:5,
  },
  {
    id: 8,
    contest_name: "b",
    contest_image: "test8",
    registrant: "호갱8",
    registrant_image: "test8",
    resgist_date: new Date(2023, 0, 3, 1, 31, 9, 22),
    hits: 9,
    thumbs: 5,
    scrap:0,
  },
  {
    id: 9,
    contest_name: "m",
    contest_image: "test8",
    registrant: "호갱9",
    registrant_image: "test5",
    resgist_date: new Date(2023, 0, 2, 1, 31, 9, 22),
    hits: 10,
    thumbs: 4,
    scrap:1,
  },
  {
    id: 10,
    contest_name: "a",
    contest_image: "test1",
    registrant: "호갱10",
    registrant_image: "test7",
    resgist_date: new Date(2023, 0, 1, 1, 31, 9, 22),
    hits: 9,
    thumbs: 1,
    scrap:3,
  },
  {
    id: 11,
    contest_name: "c",
    contest_image: "test3",
    registrant: "호갱11",
    registrant_image: "test2",
    resgist_date: new Date(2022, 11, 30, 1, 31, 9, 22),
    hits: 8,
    thumbs: 2,
    scrap:2,
  },
  {
    id: 12,
    contest_name: "v",
    contest_image: "test6",
    registrant: "호갱12",
    registrant_image: "test6",
    resgist_date: new Date(2022, 11, 27, 1, 31, 9, 22),
    hits: 7,
    thumbs: 3,
    scrap:1,
  },
];

export function getIdeaContests() {
  return ideacontest;
}